name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vuepress to GitHub Pages
      uses: testthedocs/github-pages-deploy-action@0.0.3
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: docs/.vuepress/dist/ # The folder, the action should deploy.
        BUILD_SCRIPT: npm install && npm run docs:build # The build script the action should run prior to deploying.
